{{- $fullname := include "hasura.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-migrations
  namespace: {​{​ .Release.Namespace }​}​
binaryData:
{{- range $path, $bytes := .Files.Glob (printf "migrations/**") }}
  {{- $finalPath := (index (regexSplit "migrations/" ($path) -1) 1) }}
  # finalPath: {{ $finalPath }}
{{ sha256sum $finalPath | indent 2 }}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
{{- end }}
