{{- $username := coalesce .Values.postgresql.postgresqlUsername .Values.pgClient.external.username "postgres" -}}
{{- $password := include "hasura.postgresPassword" . -}}
{{- $port := (coalesce .Values.postgresql.servicePort .Values.pgClient.external.port 5432) | int -}}
{{- $host := ternary (printf "%s-postgresql" .Release.Name) .Values.pgClient.external.host .Values.postgresql.enabled  -}}
{{- $db := coalesce .Values.postgresql.postgresqlDatabase .Values.pgClient.external.database "hasura" -}}

{{- $metadata_username := ternary .Values.metadata.username $username .Values.metadata.external  -}}
{{- $metadata_password := ternary .Values.metadata.password $password .Values.metadata.external  -}}
{{- $metadata_port := ternary .Values.metadata.port $port .Values.metadata.external  -}}
{{- $metadata_host := ternary .Values.metadata.host $host .Values.metadata.external  -}}
{{- $metadata_db := ternary .Values.metadata.database $db .Values.metadata.external  -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
data:
  postgresql-password: {{ $password | b64enc | quote }}
  databaseUrl: {{ (printf "postgres://%s:%s@%s:%d/%s" $username $password $host $port $db) | b64enc | quote }}
  metadataUrl: {{ (printf "postgres://%s:%s@%s:%d/%s" $metadata_username $metadata_password $metadata_host $metadata_port $metadata_db) | b64enc | quote }}
