apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key-staging
    solvers:
    {{- if .Values.cert.solvers }}
      {{- toYaml .Values.cert.solvers | nindent 6 }}
    {{- else }}
      - http01:
          ingress:
            class: traefik-cert-manager  
    {{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key 
    solvers:
    {{- if .Values.cert.solvers }}
      {{- toYaml .Values.cert.solvers | nindent 6 }}
    {{- else }}
      - http01:
          ingress:
            class: traefik-cert-manager  
    {{- end }}
