apiVersion: v2
description: a dummy project
name: dummy
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: simple-http
    repository: file://../../charts/simple-http
    version: "*"
    alias: web
    condition: web.enabled
  - name: simple-http
    alias: node
    version: "*"
    repository: file://../../charts/simple-http
    condition: node.enabled
