name: deploy helm charts
on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '*/helm/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package global charts
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package charts/* --dependency-update --destination dist
      - name: Package project charts
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            shopt -s nullglob
            for f in */helm; do helm package $f --dependency-update --destination dist; done
      - name: Index
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo index --url https://charts.platy.dev dist
      - name: redirect
        run: |
          sudo tee dist/index.html > /dev/null << END
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; URL=https://platy.dev/charts/" />
            </head>
            <body>Redirecting...</body>
          </html>
          END
      - name: artifacthub-repo
        run: cp charts/artifacthub-repo.yaml dist/
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          github-comment: false
          vercel-org-id: ${{ secrets.VERCEL_CHARTS_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_CHARTS_PROJECT_ID}} #Required 
          working-directory: ./dist
          alias-domains: | #Optional
            charts.platy.dev