name: deploy helm charts
on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: charts/docs/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Package
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package charts/* --dependency-update --destination dist
      - name: Index
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo index --url https://charts.platy.dev dist
      - name: redirect
        run: |
          ls dist
          sudo tee dist/index.html > /dev/null << END
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; URL=https://platy.dev/charts/" />
            </head>
            <body>Redirecting...</body>
          </html>
          END
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_CHARTS_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_CHARTS_PROJECT_ID}} #Required 
          working-directory: ./dist
          alias-domains: | #Optional
            charts.platy.dev