name: deploy platy.dev website
on:
  push:
    branches:
      - master
    paths:
      - 'devtools/web/**'
      - 'charts/**/README.md'
      - '*/README.md'
      - '*/helm/README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: devtools/web/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: build
        run: |
          cd documentation
          yarn
          yarn build
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_PLATYDEV_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PLATYDEV_PROJECT_ID}} #Required 
          working-directory: ./devtools/web/dist
          alias-domains: | #Optional
            platy.dev